### ISSUE TITLE
Riot 0.17.3 is out

### ISSUE THREAD

**Issue by akontsevich** [taw00/riot-rpm#17]
2 weeks without new versions - please upgrade! :)

**Comment by DJViking** [comment]
Yes, please update the RPMs. The OpenSUSE RPM is currently 0.16.6-0.1.testing.suse.lp150.taw0

**Comment by taw00** [comment]
I'm challenged with a build environment that is no longer building Suse RPMs.
And DJViking? You are using LP and not Tumbleweed?

**Comment by DJViking** [comment]
I am using OpenSUSE Leap 42.3

**Comment by taw00** [comment]
I will likely build for 15.0 and tumbleweed and that is that (like I have previously).
Hopefully in the next couple days I can put this behind me. Busy busy.

**Comment by DJViking** [comment]
Thanks. I am planning an upgrade to Leap 15 soon.

**Comment by DJViking** [comment]
I have upgraded my OpenSUSE Leap to Leap 15.
The README now says support OpenSUSE Leap 15

There has not yet been any new Riot RPM for 0.17.x. I am still on 0.16.6
https://keybase.pub/toddwarner/repo/riot-opensuse/leap/x86_64/

I tried building the source RPM my self on Leap 15. It got an error.
https://github.com/taw00/riot-rpm/blob/master/source/SRPMS/riot-0.17.9-1.fc29.taw.src.rpm
rpmbuild --rebuild riot-0.17.9-1.fc29.taw.src.rpm

    11% building modules 9/29 modules 20 active ...react-sdk/lib/settings/SettingsStore.jsModuleNotFoundError: Module not found: Error: Can't resolve 'gemini-scrollbar/gemini-scrollbar.css' in '/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/src/vector'
        at factory.create (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/webpack/lib/Compilation.js:814:10)
        at factory (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
        at resolver (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
        at asyncLib.parallel (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
        at /home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/neo-async/async.js:2825:7
        at /home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/neo-async/async.js:6886:13
        at normalResolver.resolve (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
        at doResolve (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
        at hook.callAsync (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
        at _fn0 (eval at create (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
        at resolver.doResolve (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
        at hook.callAsync (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
        at _fn0 (eval at create (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
        at hook.callAsync (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
        at _fn0 (eval at create (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
        at resolver.doResolve (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
        at hook.callAsync (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
        at _fn42 (eval at create (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:390:1)
        at resolver.doResolve (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:37)
        at hook.callAsync (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
        at _fn0 (eval at create (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
        at hook.callAsync (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
        at _fn0 (eval at create (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
        at args (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/enhanced-resolve/lib/forEachBail.js:30:14)
        at hook.callAsync (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
        at _fn0 (eval at create (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
        at resolver.doResolve (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
        at hook.callAsync (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
        at _fn0 (eval at create (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
        at hook.callAsync (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
        at _fn0 (eval at create (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
        at resolver.doResolve (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
        at hook.callAsync (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
        at _fn43 (eval at create (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:402:1)
        at hook.callAsync (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
        at _fn0 (eval at create (/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    resolve 'gemini-scrollbar/gemini-scrollbar.css' in '/home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/src/vector'
    Parsed request is a module
    using description file: /home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/package.json (relative path: ./src/vector)
        Field 'browser' doesn't contain a valid alias configuration
        resolve as module
        /home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/src/vector/node_modules doesn't exist or is not a directory
        /home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/src/node_modules doesn't exist or is not a directory
        /home/sverre/rpmbuild/BUILD/riot-0.17/node_modules doesn't exist or is not a directory
        /home/sverre/rpmbuild/BUILD/node_modules doesn't exist or is not a directory
        /home/sverre/rpmbuild/node_modules doesn't exist or is not a directory
        /home/sverre/node_modules doesn't exist or is not a directory
        /home/node_modules doesn't exist or is not a directory
        /node_modules doesn't exist or is not a directory
        looking for modules in /home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules
            using description file: /home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/package.json (relative path: ./node_modules)
            Field 'browser' doesn't contain a valid alias configuration
            using description file: /home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/package.json (relative path: ./node_modules/gemini-scrollbar/gemini-scrollbar.css)
                no extension
                Field 'browser' doesn't contain a valid alias configuration
                /home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/gemini-scrollbar/gemini-scrollbar.css doesn't exist
                .wasm
                Field 'browser' doesn't contain a valid alias configuration
                /home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/gemini-scrollbar/gemini-scrollbar.css.wasm doesn't exist
                .mjs
                Field 'browser' doesn't contain a valid alias configuration
                /home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/gemini-scrollbar/gemini-scrollbar.css.mjs doesn't exist
                .js
                Field 'browser' doesn't contain a valid alias configuration
                /home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/gemini-scrollbar/gemini-scrollbar.css.js doesn't exist
                .json
                Field 'browser' doesn't contain a valid alias configuration
                /home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/gemini-scrollbar/gemini-scrollbar.css.json doesn't exist
                as directory
                /home/sverre/rpmbuild/BUILD/riot-0.17/riot-web-0.17.9/node_modules/gemini-scrollbar/gemini-scrollbar.css doesn't exist
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! riot-web@0.17.9 build:bundle: `cross-env NODE_ENV=production webpack-cli -p --progress --bail --mode production`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the riot-web@0.17.9 build:bundle script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/sverre/.npm/_logs/2019-02-07T13_12_49_381Z-debug.log
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! riot-web@0.17.9 build: `npm run build:js-sdk && npm run build:react-sdk && npm run reskindex && npm run build:res && npm run build:bundle`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the riot-web@0.17.9 build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/sverre/.npm/_logs/2019-02-07T13_12_49_395Z-debug.log

**Comment by taw00** [comment]
I am kind of at a loss as to how to proceed. If someone can get this to build on OpenSUSE, I would be more than appreciative.

**Comment by xloem** [comment]
I tried to replicate this, but the quoted source rpm builds fine for me on a new install of Leap 15.  Maybe there was a bug in a dependency that has since been resolved.

I also didn't have some of the issues that are quoted in the specs file -- e.g. I could also build by hand fine without doing any ssl dances.

Notably, Riot 1.0 is out now.

**Comment by akontsevich** [comment]
Still no rpms for SUSE: https://keybase.pub/toddwarner/pub/srpms/

**Comment by xloem** [comment]
https://keybase.pub/toddwarner/pub/srpms/riot-0.17.9-1.fc29.taw.src.rpm builds on SUSE for me.  It is now outdated.

**Comment by akontsevich** [comment]
Yes, builds fine for me too. Need 1.0.1 for now :)

**Comment by xloem** [comment]
I tried building 1.0.0/1.0.1 on Leap and it builds but Electron coredumps with a SIGTRAP whenever I run it. I tried debugging with gdb and gdb itself crashed!  I was running inside Docker and I'm not sure whether it's Docker or OpenSUSE.  UPDATE: I tried with a full VM and it builds and runs fine on OpenSUSE Leap 15 with current specfile.

**Comment by DJViking** [comment]
I managed to build the 1.0.0 today on my OpenSUSE Leap 15 home computer.
https://keybase.pub/toddwarner/pub/srpms/riot-1.0.0-1.fc29.taw.src.rpm
It also starts up fine.
Will try more tomorrow at work where we have Riot installed.

<br>
Noticed during rpmbuild --rebuild:

    Update available 5.6.0 → 6.8.0
    Run npm i npm to update

**Comment by akontsevich** [comment]
Yes, fedora srpm builds and works fine on SUSE. Could upgrade to 1.0.1 now.

**Comment by xloem** [comment]
#21 https://github.com/taw00/riot-rpm/raw/8d1fdf866c3f4de5ac80209652fed2b29410dcab/source/SRPMS/riot-1.0.1-1.fc29.taw.src.rpm

**Comment by DJViking** [comment]
Strange. My work computer, also an OpenSUSE Leap 15, It failed building riot-1.0.1

    • building        target=tar.gz arch=x64 file=electron_app/dist/riot-web-1.0.1.tar.gz
    Error: Exit code: 2. Command failed: /home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/7zip-bin/linux/x64/7za rn /tmp/t-f51Zke/0.tar linux-unpacked riot-web-1.0.1

    System ERROR:
    E_FAIL

        at /home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/builder-util/src/util.ts:126:16
        at ChildProcess.exithandler (child_process.js:288:5)
        at emitTwo (events.js:126:13)
        at ChildProcess.emit (events.js:214:7)
        at maybeClose (internal/child_process.js:915:16)
        at Socket.stream.socket.on (internal/child_process.js:336:11)
        at emitOne (events.js:116:13)
        at Socket.emit (events.js:211:7)
        at Pipe._handle.close [as _onclose] (net.js:561:12)
    From previous event:
        at _tar (/home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/app-builder-lib/out/targets/archive.js:122:15)
        at tar (/home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/app-builder-lib/out/targets/archive.js:76:15)
        at /home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/app-builder-lib/src/targets/ArchiveTarget.ts:41:13
    From previous event:
        at ArchiveTarget.build (/home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/app-builder-lib/src/targets/ArchiveTarget.ts:16:44)
        at Function.buildAsyncTargets (/home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
        at LinuxPackager.packageInDistributableFormat (/home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
        at /home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/app-builder-lib/src/platformPackager.ts:114:10
        at Generator.next (<anonymous>)
        at runCallback (timers.js:810:20)
        at tryOnImmediate (timers.js:768:5)
        at processImmediate [as _immediateCallback] (timers.js:745:5)
    From previous event:
        at LinuxPackager.pack (/home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
        at /home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/app-builder-lib/src/packager.ts:430:24
        at Generator.next (<anonymous>)
        at xfs.stat (/home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
        at /home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/graceful-fs/polyfills.js:287:18
        at FSReqWrap.oncomplete (fs.js:153:5)
    From previous event:
        at Packager.doBuild (/home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/app-builder-lib/src/packager.ts:396:24)
        at /home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/app-builder-lib/src/packager.ts:366:57
        at Generator.next (<anonymous>)
        at /home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/graceful-fs/graceful-fs.js:99:16
        at /home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/graceful-fs/graceful-fs.js:43:10
        at FSReqWrap.oncomplete (fs.js:135:15)
    From previous event:
        at Packager._build (/home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/app-builder-lib/src/packager.ts:335:133)
        at /home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/app-builder-lib/src/packager.ts:331:23
        at Generator.next (<anonymous>)
        at runCallback (timers.js:810:20)
        at tryOnImmediate (timers.js:768:5)
        at processImmediate [as _immediateCallback] (timers.js:745:5)
    From previous event:
        at Packager.build (/home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/app-builder-lib/src/packager.ts:288:14)
        at build (/home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/app-builder-lib/src/index.ts:59:28)
        at build (/home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/electron-builder/src/builder.ts:227:10)
        at then (/home/sverre/rpmbuild/BUILD/riot-1.0/riot-web-1.0.1/node_modules/electron-builder/src/cli/cli.ts:46:19)
        at <anonymous>

**Comment by akontsevich** [comment]
1.0.1 builds fine in Tumbleweed.

**Comment by DJViking** [comment]
Yesterday I got it building on OpenSUSE Leap 15 at my home computer. Today on my work computer it failed, but when I changed the spec file to remove setting the NPM registry I got it building. It would instead use our own npm registry proxy on Nexus.

**Comment by taw00** [comment]
I got Tumbleweed working (and it is signed and in the repo)... I.e., It simply started building again (as of 1.0.1 at least). I don't know what is up with that.

As for LP... I will study that a bit closer sometime this week. @DJViking --- if you could send me your spec file that would be helpful.

**Comment by DJViking** [comment]
On my home computer OpenSUSE Leap 15, I didn't make any changes to the spec file and got no problem building.
On my work computer OpenSUSE Leap 15, I commented out the npm registry in the spec file to get it to build, because we use Sonatype Nexus at work for NPM registry proxy.

**Comment by akontsevich** [comment]
> I got Tumbleweed working (and it is signed and in the repo)... I.e., It simply started building again (as of 1.0.1 at least). I don't know what is up with that.

@taw00, thanks! Works now!

**Comment by akontsevich** [comment]
@taw00, again no latest versions for openSUSE?

**Comment by taw00** [comment]
They are failing to build once again... therefore... lagging.

**Comment by akontsevich** [comment]
I was unable to build Fedora SRPM on SUSE as well.

**Comment by taw00** [comment]
@akontsevich  Got it working... and this time... less hackish! Stay tuned. I will update this comment when it lands in the COPR repos.

BAM! Tumbleweed and Leap both in testing and production COPR repos.... and building just fine! Woot! First time from EPEL to Fedora to Leap to Tumbleweed without weirdness in a long long time.

**Comment by taw00** [comment]
I am closing this as complete! EPEL to Fedora to Leap to Tumbleweed... build fine.

**Comment by taw00** [comment]
I am closing this as complete! EPEL to Fedora to Leap to Tumbleweed... build fine.

**Comment by akontsevich** [comment]
Thanks!

**Comment by DJViking** [comment]
Thanks!

**Comment by DJViking** [comment]
> I am closing this as complete! EPEL to Fedora to Leap to Tumbleweed... build fine.
Is there published new RPMs for OpenSUSE? The instructions on README still gives only the 0.16 version of Riot.

**Comment by akontsevich** [comment]
Read README.md of this repo: you need to install latest [toddpkgs-riot-repo.suse.tw.rpm](https://github.com/taw00/riot-rpm/blob/master/toddpkgs-riot-repo.suse.tw.rpm):

Prep (OpenSuse Tumbleweed)...
```
# Snag the repository configuration (should only need to do once)
sudo rpm --import https://keybase.io/toddwarner/key.asc
sudo zypper install https://github.com/taw00/riot-rpm/raw/master/toddpkgs-riot-repo.suse.tw.rpm
sudo zypper modifyrepo -er "riot-stable"
```
Install...
```
# Clean out the cache in case the change didn't get picked up
sudo zypper refresh
# Install riot
sudo zypper install riot
```
