### ISSUE TITLE
Renderer crash on Tumbleweed

### ISSUE THREAD

**Issue by stryan** [taw00/riot-rpm#49]
For a couple days now I haven't been able to use element on an up-to-date instance of OpenSUSE TW. Running the program just results in a blank window. Looks like it can't find a localization file, resulting in the renderer crashing.

Does this look like an issue with the package, or something on my machine? I'm not familiar with Electron localization to know if those files are bundled or something. Runtime log below:

```
stryan@host:  element --enable-logging 
/home/stryan/.config/Element exists: no
/home/stryan/.config/Riot exists: yes
Using legacy user data path: /home/stryan/.config/Riot
[8308:1001/115056.978289:WARNING:archive.cc(151)] Opening /usr/share/io.element.element/resources/app.asar/webapp.asar: FILE_ERROR_NOT_A_DIRECTORY
No update_base_url is defined: auto update is disabled
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: Cannot find module './i18n/strings/en-us.json'
Require stack:
- /usr/share/io.element.element/resources/app.asar/lib/language-helper.js
- /usr/share/io.element.element/resources/app.asar/lib/tray.js
- /usr/share/io.element.element/resources/app.asar/lib/electron-main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at AppLocalization.fetchTranslationJson (/usr/share/io.element.element/resources/app.asar/lib/language-helper.js:76:20)
    at /usr/share/io.element.element/resources/app.asar/lib/language-helper.js:89:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/usr/share/io.element.element/resources/app.asar/lib/language-helper.js:88:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/io.element.element/resources/app.asar/lib/language-helper.js',
    '/usr/share/io.element.element/resources/app.asar/lib/tray.js',
    '/usr/share/io.element.element/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Resetting the UI components after locale change
Resetting the UI components after locale change
[8379:1001/115057.111513:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.

**Comment by barathrm** [comment]
Seems to be this https://github.com/vector-im/element-web/issues/19153 and https://github.com/vector-im/element-web/issues/19169#issuecomment-931518447
which is supposed to be fixed in element nightly. Guess we'll have to wait.

**Comment by stryan** [comment]
Looks like the changes came through and I can open it now. I still see the locale issues though, so before I close this @barathrm are you still having the issue?

**Comment by barathrm** [comment]
The latest version fixes startup/the white screen for me as well 👌

**Comment by stryan** [comment]
Great! Closing then.
