### ISSUE TITLE
does not work on fedora 35

### ISSUE THREAD

**Issue by damnms** [taw00/riot-rpm#50]
[oli@fedora ~]$ element 
Seshat unexpected error: Error: libsqlcipher-3.15.2.so.0: Kann die Shared-Object-Datei nicht Ã¶ffnen: Datei oder Verzeichnis nicht gefunden
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/share/io.element.element/resources/app.asar/node_modules/matrix-seshat/lib/index.js:16:22)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
/home/oli/.config/Element exists: yes
/home/oli/.config/Riot exists: no
No update_base_url is defined: auto update is disabled
Fetching translation json for locale: en_EN
Changing application language to de
Fetching translation json for locale: de
Resetting the UI components after locale change
Resetting the UI components after locale change
[15274:1002/132026.290449:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)

**Comment by damnms** [comment]
the workaround is to execute that with element --disable-seccomp-filter-sandbox
has something to do with the used electron version

maybe if someone could recompile that and use the latest electron version that fixes that, would be awesome
